### ISSUE TITLE
Is it not possible to login to a migrated minecraft account?

### ISSUE THREAD

**Issue by TheOnlyWayUp** [samcarsonx/yggdrasil-py#3]
I'm interested to know, and if it would be possible to log into a migrated Microsoft Account. The current library raises an error if you try this, and I want to know if there's a way to do it, or if it will be added soon.

**Comment by samcarsonx** [comment]
I haven't worked on this in over a year and sadly I don't have the time to at the moment. Maybe I'll come back to it in the near future? There is certainly a way to do it though -[Here's how the Microsoft OAuth flow works.](https://wiki.vg/Microsoft_Authentication_Scheme)
